# Site settings
title: "One spacebar behind"
description: "A blog about me going b!!! and some other things"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://berserker1.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Aaryan Bhagat
user_title: berserker1
email: aaryanbhagat377@gmail.com
twitter_username:
github_username: berserker1
linkedin_public_url: https://www.linkedin.com/in/aaryan-bhagat-b42b2515a/ # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: aaryan_bhagat
profile_picture: https://raw.githubusercontent.com/berserker1/berserker1.github.io/master/embarrasment.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  # - name: asciilang
  #   url: https://github.com/victorvoid/asciilang
  # - name: vim-frontend
  #   url: https://github.com/victorvoid/vim-frontend
  # - name: generator-capybara
  #   url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules','package-lock.json']
